/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Cats]
(
[CatId] [int] NULL,
[CatName] [varchar] (255) NULL,
[Phone] [varchar] (255) NULL
)
GO
